FPT-Book/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace FPT_Book.Models
{
    public class Author
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Image")]
        public string ProfilepictureURL { get; set; }

        [Display(Name = "FullName")]
        public string FullName { get; set; }

        [Display(Name = "Biography")]
        public string Bio { get; set; }

        //Relationships
        public List<Author_Book> Authors_Books { get; set; }
    }
}

FPT-Book/Models/Author_Book.cs
namespace FPT_Book.Models
{
    public class Author_Book
    {
        public int BookId { get; set; }
        public Book Book { get; set; }

        public int AuthorId { get; set; }
        public Author Author { get; set; }
    }
}

FPT-Book/Models/Book.cs
using FPT_Book.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FPT_Book.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public DateTime PublicDate { get; set; }
        public BookCategory BookCategory { get; set; }

        //Relationships
        public List<Author_Book> Authors_Books { get; set; }

        //Bookstore
        public int BookStoreId { get; set; }
        [ForeignKey("BookStoreId")]
        public Bookstore Bookstore { get; set; }

        //Publisher
        public int PublisherID { get; set; }
        [ForeignKey("PublisherID")]
        public Publisher Publisher { get; set; }
    }
}

FPT-Book/Models/Bookstore.cs
using System.ComponentModel.DataAnnotations;

namespace FPT_Book.Models
{
    public class Bookstore
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Image")]
        public string Logo { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }

        //Relationships
        public List<Book> Books { get; set; } 
    }
}

FPT-Book/Models/ErrorViewModel.cs
namespace FPT_Book.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FPT-Book/Models/Publisher.cs
using System.ComponentModel.DataAnnotations;

namespace FPT_Book.Models
{
    public class Publisher
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Image")]
        public string ProfilepictureURL { get; set; }
        [Display(Name = "FullName")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        public string Bio { get; set; }

        //Relationships
        public List<Book> Books { get; set; }
    }
}

FPT-Book/Controllers/AuthorsController.cs
using FPT_Book.Data;
using Microsoft.AspNetCore.Mvc;

namespace FPT_Book.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly AppDBContext _context;

        public AuthorsController(AppDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Authors.ToList();
            return View("AuthorIndex", data);
        }
    }
}

FPT-Book/Controllers/BookStoresController.cs
using FPT_Book.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPT_Book.Controllers
{
    public class BookStoresController : Controller
    {
        private readonly AppDBContext _context;

        public BookStoresController(AppDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allBookStores = await _context.Bookstores.ToListAsync();
            return View("BookStoreIndex", allBookStores);
        }
    }
}

FPT-Book/Controllers/BooksController.cs
using FPT_Book.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPT_Book.Controllers
{
    public class BooksController : Controller
    {
        private readonly AppDBContext _context;

        public BooksController(AppDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allBooks = await _context.Books.Include(n => n.Bookstore).OrderBy(n => n.Name).ToListAsync();
            return View("BookIndex", allBooks);
        }
    }
}

FPT-Book/Controllers/PublishersController.cs
using FPT_Book.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPT_Book.Controllers
{
    public class PublishersController : Controller
    {
        private readonly AppDBContext _context;

        public PublishersController(AppDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allPublishers = await _context.Publishers.ToListAsync();
            return View("PublisherIndex", allPublishers);
        }
    }
}

FPT-Book/Views/Authors/AuthorIndex.cshtml
@model IEnumerable<Author>

@{
    ViewData["Title"]="List of Authors";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilepictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {*@
                        <th>Actions</th>
                    @*}*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ProfilepictureURL" alt="@item.FullName" style="max-width: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))*@
                    @*{*@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    @*}*@

                </tr>
                }
            </tbody>

        </table>
    </div>

</div>

FPT-Book/Views/BookStores/BookStoreIndex.cshtml
@model IEnumerable<Bookstore>

@{
    ViewData["Title"]="List of Bookstores";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Logo)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {*@
                        <th>Actions</th>
                    @*}*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.Logo" alt="@item    .Name" style="max-width: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))*@
                    @*{*@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    @*}*@

                </tr>
                }
            </tbody>

        </table>
    </div>

</div>

FPT-Book/Views/Books/BookIndex.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"]="List of Books";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {*@
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    @*}*@
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Bookstore: </b>@item.Bookstore.Name </p>
                            <p class="card-text"><b>Category: </b>@item.BookCategory</p>
                            <p class="card-text"><b>Public Date: </b>@item.PublicDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.PublicDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

FPT-Book/Views/Publishers/PublisherIndex.cshtml
@model IEnumerable<Publisher>

@{
    ViewData["Title"]="List of Publishers";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilepictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {*@
                        <th>Actions</th>
                    @*}*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ProfilepictureURL" alt="@item.FullName" style="max-width: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))*@
                    @*{*@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    @*}*@

                </tr>
                }
            </tbody>

        </table>
    </div>

</div>

FPT-Book/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPT_Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FPT_Book.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Books" asp-action="Index">FPT_Book</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"><i class="bi bi-film"></i> Books</a>
                        </li>

                       <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Management
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="BookStrores" asp-action="Index"><i class="bi bi-camera-reels"></i> BookStrores</a>
                                        <a class="dropdown-item" asp-controller="Publishers" asp-action="Index"><i class="bi bi-headset"></i> Publishers</a>
                                        <a class="dropdown-item" asp-controller="Authors" asp-action="Index"><i class="bi bi-person-square"></i> Authors</a>
                                    </div>
                                </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Books" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    @*<ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>*@

                    @*<partial name="_Identity.cshtml" />*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FPT_Book 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>